name: 抖音火山

on:
  workflow_dispatch:
  schedule:
    - cron: '5 */6 * * *'
    watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        BAIDU_COOKIE: ${{ secrets.BAIDU_COOKIE }}
        TZ: Asia/shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【火山】'
        run: |
          node Task/huoshan.js
        env:
          HSURL: ${{ secrets.HSURL }}
          HSHEADER: ${{ secrets.HSHEADER }}
          HSBODY: ${{ secrets.HSBODY }}
          PLAYURL: ${{ secrets.PLAYURL }}
          PLAYHEADER: ${{ secrets.PLAYHEADER }}
          PLAYBODY: ${{ secrets.PLAYBODY }}