name: 抖音火山

on:
    workflow_dispatch:
    schedule:
        - cron: "0/5 0-16 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行【抖音火山】"
              if: env.HSURL
        run: |
          node Task/huoshan.js
        env:
          HSURL: ${{ secrets.HSURL }}
          HSHEADER: ${{ secrets.HSHEADER }}
          HSBODY: ${{ secrets.HSBODY }}
          PLAYURL: ${{ secrets.PLAYURL }}
          PLAYHEADER: ${{ secrets.PLAYHEADER }}
          PLAYBODY: ${{ secrets.PLAYBODY }}